[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [ # do not change these remappings otherwise new create2 addresses will be generated, see https://github.com/foundry-rs/foundry/issues/7826
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
